strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      buildOs: 'linux'
    mac:
      imageName: 'macos-10.14'
      buildOs: 'macos'
    windows:
      imageName: 'vs2017-win2016'
      buildOs: 'win'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: 'npm install'

- script: 'npm run dist'

- task: CopyFiles@2
  inputs:
    contents: 'dist/*.*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'launcher-bootstrap-$(buildOs)'